/**
 * Ypsilon Script Code Generator - OOP, Strictly-Typed, Brace-Based
 * Transpiles AST to Arduino C++ code
 */

class CodeGenerator {
  constructor(ast) {
    this.ast = ast;
    this.classes = [];
    this.globalVariables = [];
    this.functions = [];
    this.setupStatements = [];
    this.loopStatements = [];
    this.indent = 0;
    this.needsSerial = false;
  }

  generate() {
    // First pass: analyze the AST to detect features we need
    this.analyzeAST(this.ast);
    
    // Second pass: process and generate code
    this.processProgram(this.ast);
    return this.buildArduinoCode();
  }

  analyzeAST(node) {
    if (!node) return;
    
    if (node.type === 'CallExpression' && node.callee && node.callee.name === 'print') {
      this.needsSerial = true;
    }
    
    // Recursively check all nodes
    if (Array.isArray(node)) {
      node.forEach(n => this.analyzeAST(n));
    } else if (typeof node === 'object') {
      Object.values(node).forEach(value => {
        if (value && typeof value === 'object') {
          this.analyzeAST(value);
        }
      });
    }
  }

  processProgram(program) {
    for (const stmt of program.body) {
      this.processTopLevelStatement(stmt);
    }
  }

  processTopLevelStatement(stmt) {
    if (stmt.type === 'ClassDeclaration') {
      this.classes.push(stmt);
    } else if (stmt.type === 'FunctionDeclaration') {
      // Special handling for start()/setup() and loop()
      if (stmt.name === 'setup' || stmt.name === 'start') {
        this.setupStatements = stmt.body;
      } else if (stmt.name === 'loop') {
        this.loopStatements = stmt.body;
      } else {
        this.functions.push(stmt);
      }
    } else if (stmt.type === 'VariableDeclaration') {
      this.globalVariables.push(stmt);
    }
  }

  buildArduinoCode() {
    let code = '// Generated by Ypsilon Script Compiler\n';
    code += '// https://github.com/ycharfi09/ypsilon-script\n\n';
    
    // Add Arduino library includes
    code += '#include <Arduino.h>\n\n';

    // Class declarations
    if (this.classes.length > 0) {
      code += '// Class Declarations\n';
      for (const cls of this.classes) {
        code += this.generateClassDeclaration(cls) + '\n\n';
      }
    }

    // Global variables
    if (this.globalVariables.length > 0) {
      code += '// Global Variables\n';
      for (const varDecl of this.globalVariables) {
        code += this.generateVariableDeclaration(varDecl) + '\n';
      }
      code += '\n';
    }

    // Function declarations
    if (this.functions.length > 0) {
      code += '// Function Declarations\n';
      for (const func of this.functions) {
        code += this.generateFunctionDeclaration(func) + '\n\n';
      }
    }

    // Setup function
    code += 'void setup() {\n';
    this.indent = 1;
    
    // Add Serial.begin if print() is used
    if (this.needsSerial) {
      code += this.getIndent() + 'Serial.begin(9600);\n';
    }
    
    if (this.setupStatements.length > 0) {
      for (const stmt of this.setupStatements) {
        code += this.generateStatement(stmt);
      }
    }
    this.indent = 0;
    code += '}\n\n';

    // Loop function
    code += 'void loop() {\n';
    this.indent = 1;
    if (this.loopStatements.length > 0) {
      for (const stmt of this.loopStatements) {
        code += this.generateStatement(stmt);
      }
    }
    this.indent = 0;
    code += '}\n';

    return code;
  }

  generateClassDeclaration(cls) {
    let code = `class ${cls.name} {\n`;
    code += 'public:\n';
    
    // Generate properties
    for (const prop of cls.properties) {
      code += '  ' + this.mapType(prop.propertyType) + ' ' + prop.name;
      if (prop.init) {
        // Note: In-class initialization requires C++11
        code += ' = ' + this.generateExpression(prop.init);
      }
      code += ';\n';
    }
    
    if (cls.properties.length > 0 && (cls.constructor || cls.methods.length > 0)) {
      code += '\n';
    }
    
    // Generate constructor
    if (cls.constructor) {
      code += '  ' + cls.name + '(';
      code += cls.constructor.params.map(p => 
        this.mapType(p.type) + ' ' + p.name
      ).join(', ');
      code += ') {\n';
      
      this.indent = 2;
      for (const stmt of cls.constructor.body) {
        code += this.generateStatement(stmt);
      }
      this.indent = 0;
      
      code += '  }\n';
      
      if (cls.methods.length > 0) {
        code += '\n';
      }
    }
    
    // Generate methods
    for (let i = 0; i < cls.methods.length; i++) {
      const method = cls.methods[i];
      code += '  ' + this.mapType(method.returnType) + ' ' + method.name + '(';
      code += method.params.map(p => 
        this.mapType(p.type) + ' ' + p.name
      ).join(', ');
      code += ') {\n';
      
      this.indent = 2;
      for (const stmt of method.body) {
        code += this.generateStatement(stmt);
      }
      this.indent = 0;
      
      code += '  }';
      if (i < cls.methods.length - 1) {
        code += '\n\n';
      } else {
        code += '\n';
      }
    }
    
    code += '};';
    return code;
  }

  generateFunctionDeclaration(func) {
    const returnType = this.mapType(func.returnType);
    
    let code = `${returnType} ${func.name}(`;
    code += func.params.map(p => 
      this.mapType(p.type) + ' ' + p.name
    ).join(', ');
    code += ') {\n';
    
    this.indent++;
    for (const stmt of func.body) {
      code += this.generateStatement(stmt);
    }
    this.indent--;
    
    code += '}';
    return code;
  }

  mapType(type) {
    const typeMap = {
      'int': 'int',
      'float': 'float',
      'bool': 'bool',
      'string': 'String',
      'void': 'void'
    };
    // If it's not a built-in type, assume it's a class name
    return typeMap[type] || type;
  }

  generateStatement(stmt) {
    switch (stmt.type) {
      case 'VariableDeclaration':
        return this.getIndent() + this.generateVariableDeclaration(stmt) + '\n';
      case 'ExpressionStatement':
        return this.getIndent() + this.generateExpression(stmt.expression) + ';\n';
      case 'IfStatement':
        return this.generateIfStatement(stmt);
      case 'WhileStatement':
        return this.generateWhileStatement(stmt);
      case 'ForStatement':
        return this.generateForStatement(stmt);
      case 'RepeatStatement':
        return this.generateRepeatStatement(stmt);
      case 'ReturnStatement':
        return this.generateReturnStatement(stmt);
      default:
        return '';
    }
  }

  generateVariableDeclaration(varDecl) {
    const typePrefix = varDecl.kind === 'const' ? 'const ' : '';
    const type = this.mapType(varDecl.varType);
    let code = `${typePrefix}${type} ${varDecl.name}`;
    if (varDecl.init) {
      code += ' = ' + this.generateExpression(varDecl.init);
    }
    return code + ';';
  }

  generateIfStatement(stmt) {
    let code = this.getIndent() + 'if (' + this.generateExpression(stmt.test) + ') {\n';
    this.indent++;
    for (const s of stmt.consequent) {
      code += this.generateStatement(s);
    }
    this.indent--;
    code += this.getIndent() + '}';
    
    if (stmt.alternate) {
      code += ' else {\n';
      this.indent++;
      for (const s of stmt.alternate) {
        code += this.generateStatement(s);
      }
      this.indent--;
      code += this.getIndent() + '}';
    }
    
    code += '\n';
    return code;
  }

  generateWhileStatement(stmt) {
    let code = this.getIndent() + 'while (' + this.generateExpression(stmt.test) + ') {\n';
    this.indent++;
    for (const s of stmt.body) {
      code += this.generateStatement(s);
    }
    this.indent--;
    code += this.getIndent() + '}\n';
    return code;
  }

  generateForStatement(stmt) {
    const varType = this.mapType(stmt.varType);
    const init = this.generateExpression(stmt.init);
    const test = this.generateExpression(stmt.test);
    const update = this.generateExpression(stmt.update);
    
    let code = this.getIndent() + `for (${varType} ${stmt.variable} = ${init}; ${test}; ${update}) {\n`;
    
    this.indent++;
    for (const s of stmt.body) {
      code += this.generateStatement(s);
    }
    this.indent--;
    code += this.getIndent() + '}\n';
    return code;
  }

  generateRepeatStatement(stmt) {
    const count = this.generateExpression(stmt.count);
    
    // Generate a for loop: for (int _repeat_i = 0; _repeat_i < count; _repeat_i++)
    let code = this.getIndent() + `for (int _repeat_i = 0; _repeat_i < ${count}; _repeat_i++) {\n`;
    
    this.indent++;
    for (const s of stmt.body) {
      code += this.generateStatement(s);
    }
    this.indent--;
    code += this.getIndent() + '}\n';
    return code;
  }

  generateReturnStatement(stmt) {
    let code = this.getIndent() + 'return';
    if (stmt.argument) {
      code += ' ' + this.generateExpression(stmt.argument);
    }
    return code + ';\n';
  }

  generateExpression(expr) {
    switch (expr.type) {
      case 'Literal':
        return this.generateLiteral(expr);
      case 'Identifier':
        return expr.name;
      case 'BinaryExpression':
        return this.generateBinaryExpression(expr);
      case 'UnaryExpression':
        return this.generateUnaryExpression(expr);
      case 'AssignmentExpression':
        return this.generateExpression(expr.left) + ' = ' + this.generateExpression(expr.right);
      case 'CallExpression':
        return this.generateCallExpression(expr);
      case 'MemberExpression':
        return this.generateExpression(expr.object) + '.' + expr.property;
      case 'ThisExpression':
        return 'this';
      case 'NewExpression':
        return this.generateNewExpression(expr);
      default:
        return '';
    }
  }

  generateLiteral(expr) {
    if (expr.valueType === 'string') {
      return `"${expr.value}"`;
    } else if (expr.valueType === 'boolean') {
      return expr.value ? 'true' : 'false';
    }
    return String(expr.value);
  }

  generateBinaryExpression(expr) {
    const left = this.generateExpression(expr.left);
    const right = this.generateExpression(expr.right);
    
    // Convert operators to C++
    const operatorMap = {
      'and': '&&',
      'or': '||',
      '==': '==',
      '!=': '!=',
      '<': '<',
      '>': '>',
      '<=': '<=',
      '>=': '>=',
      '+': '+',
      '-': '-',
      '*': '*',
      '/': '/',
      '%': '%'
    };
    
    const op = operatorMap[expr.operator] || expr.operator;
    return `(${left} ${op} ${right})`;
  }

  generateUnaryExpression(expr) {
    const operatorMap = {
      'not': '!',
      '-': '-'
    };
    const op = operatorMap[expr.operator] || expr.operator;
    return `${op}(${this.generateExpression(expr.argument)})`;
  }

  generateCallExpression(expr) {
    // Safely extract callee name, checking for null
    if (!expr.callee) {
      return '';
    }
    
    let callee;
    if (expr.callee.type === 'MemberExpression') {
      callee = this.generateExpression(expr.callee);
    } else {
      callee = expr.callee.name || this.generateExpression(expr.callee);
    }
    
    const args = expr.arguments.map(arg => this.generateExpression(arg)).join(', ');
    
    // Map built-in functions to Arduino equivalents
    const builtinMap = {
      'print': 'Serial.println',
      'delay': 'delay',
      'millis': 'millis',
      'pinMode': 'pinMode',
      'digitalWrite': 'digitalWrite',
      'digitalRead': 'digitalRead',
      'analogRead': 'analogRead',
      'analogWrite': 'analogWrite'
    };
    
    const funcName = builtinMap[callee] || callee;
    
    // Mark that we need Serial if print is used
    if (callee === 'print') {
      this.needsSerial = true;
    }
    
    return `${funcName}(${args})`;
  }

  generateNewExpression(expr) {
    const args = expr.arguments.map(arg => this.generateExpression(arg)).join(', ');
    return `${expr.className}(${args})`;
  }

  getIndent() {
    return '  '.repeat(this.indent);
  }
}

module.exports = { CodeGenerator };
