/**
 * Ypsilon Script Code Generator - OOP, Strictly-Typed, Brace-Based
 * Transpiles AST to Arduino C++ code
 */

class CodeGenerator {
  constructor(ast) {
    this.ast = ast;
    this.classes = [];
    this.enums = [];
    this.structs = [];
    this.globalVariables = [];
    this.functions = [];
    this.setupStatements = [];
    this.loopStatements = [];
    this.onBlocks = [];
    this.signals = [];
    this.tasks = [];
    this.useStatements = [];
    this.loadStatements = [];
    this.aliases = [];
    this.config = null;
    this.reactVars = [];
    this.indent = 0;
    this.needsSerial = false;
    this.timeVarCounter = 0;
  }

  generate() {
    // First pass: analyze the AST to detect features we need
    this.analyzeAST(this.ast);
    
    // Second pass: process and generate code
    this.processProgram(this.ast);
    return this.buildArduinoCode();
  }

  analyzeAST(node) {
    if (!node) return;
    
    if (node.type === 'CallExpression' && node.callee && node.callee.name === 'print') {
      this.needsSerial = true;
    }
    
    // Recursively check all nodes
    if (Array.isArray(node)) {
      node.forEach(n => this.analyzeAST(n));
    } else if (typeof node === 'object') {
      Object.values(node).forEach(value => {
        if (value && typeof value === 'object') {
          this.analyzeAST(value);
        }
      });
    }
  }

  processProgram(program) {
    for (const stmt of program.body) {
      this.processTopLevelStatement(stmt);
    }
  }

  processTopLevelStatement(stmt) {
    if (stmt.type === 'ClassDeclaration') {
      this.classes.push(stmt);
    } else if (stmt.type === 'EnumDeclaration') {
      this.enums.push(stmt);
    } else if (stmt.type === 'StructDeclaration') {
      this.structs.push(stmt);
    } else if (stmt.type === 'FunctionDeclaration') {
      // Special handling for start()/setup() and loop()
      if (stmt.name === 'setup' || stmt.name === 'start') {
        this.setupStatements = stmt.body;
      } else if (stmt.name === 'loop') {
        this.loopStatements = stmt.body;
      } else {
        this.functions.push(stmt);
      }
    } else if (stmt.type === 'VariableDeclaration') {
      this.globalVariables.push(stmt);
    } else if (stmt.type === 'OnBlock') {
      this.onBlocks.push(stmt);
    } else if (stmt.type === 'SignalDeclaration') {
      this.signals.push(stmt);
    } else if (stmt.type === 'TaskDeclaration') {
      this.tasks.push(stmt);
    } else if (stmt.type === 'UseStatement') {
      this.useStatements.push(stmt);
    } else if (stmt.type === 'LoadStatement') {
      this.loadStatements.push(stmt);
    } else if (stmt.type === 'AliasStatement') {
      this.aliases.push(stmt);
    } else if (stmt.type === 'ConfigBlock') {
      this.config = stmt;
    } else if (stmt.type === 'ReactDeclaration') {
      this.reactVars.push(stmt);
    }
  }

  buildArduinoCode() {
    let code = '// Generated by Ypsilon Script Compiler\n';
    code += '// https://github.com/ycharfi09/ypsilon-script\n\n';
    
    // Add Arduino library includes
    code += '#include <Arduino.h>\n';
    
    // Add loaded libraries
    for (const load of this.loadStatements) {
      code += `#include <${load.library}.h>\n`;
    }
    code += '\n';
    
    // Add aliases as #define
    if (this.aliases.length > 0) {
      code += '// Aliases\n';
      for (const alias of this.aliases) {
        code += `#define ${alias.name} ${alias.value}\n`;
      }
      code += '\n';
    }

    // Enum declarations
    if (this.enums.length > 0) {
      code += '// Enum Declarations\n';
      for (const enumDecl of this.enums) {
        code += this.generateEnumDeclaration(enumDecl) + '\n\n';
      }
    }

    // Struct declarations
    if (this.structs.length > 0) {
      code += '// Struct Declarations\n';
      for (const structDecl of this.structs) {
        code += this.generateStructDeclaration(structDecl) + '\n\n';
      }
    }

    // Class declarations
    if (this.classes.length > 0) {
      code += '// Class Declarations\n';
      for (const cls of this.classes) {
        code += this.generateClassDeclaration(cls) + '\n\n';
      }
    }

    // Signals (using volatile bool)
    if (this.signals.length > 0) {
      code += '// Signal Declarations\n';
      for (const signal of this.signals) {
        code += `volatile bool _signal_${signal.name} = false;\n`;
      }
      code += '\n';
    }

    // React variables (using volatile)
    if (this.reactVars.length > 0) {
      code += '// Reactive Variables\n';
      for (const react of this.reactVars) {
        const typeStr = this.mapType(react.varType);
        const constStr = react.isMut ? 'volatile' : 'volatile const';
        const initStr = react.init ? ' = ' + this.generateExpression(react.init) : '';
        code += `${constStr} ${typeStr} ${react.name}${initStr};\n`;
      }
      code += '\n';
    }

    // Global variables
    if (this.globalVariables.length > 0) {
      code += '// Global Variables\n';
      for (const varDecl of this.globalVariables) {
        code += this.generateVariableDeclaration(varDecl) + '\n';
      }
      code += '\n';
    }

    // Task timing variables
    if (this.tasks.length > 0) {
      code += '// Task Timing Variables\n';
      for (const task of this.tasks) {
        if (task.interval) {
          code += `unsigned long _task_${task.name}_last = 0;\n`;
        }
      }
      code += '\n';
    }

    // Function declarations
    if (this.functions.length > 0) {
      code += '// Function Declarations\n';
      for (const func of this.functions) {
        code += this.generateFunctionDeclaration(func) + '\n\n';
      }
    }

    // Setup function
    code += 'void setup() {\n';
    this.indent = 1;
    
    // Add Serial.begin if print() is used
    if (this.needsSerial) {
      code += this.getIndent() + 'Serial.begin(9600);\n';
    }
    
    // Handle on start blocks
    for (const onBlock of this.onBlocks) {
      if (onBlock.event === 'start') {
        for (const stmt of onBlock.body) {
          code += this.generateStatement(stmt);
        }
      }
    }
    
    if (this.setupStatements.length > 0) {
      for (const stmt of this.setupStatements) {
        code += this.generateStatement(stmt);
      }
    }
    this.indent = 0;
    code += '}\n\n';

    // Loop function
    code += 'void loop() {\n';
    this.indent = 1;
    
    // Handle on loop blocks
    for (const onBlock of this.onBlocks) {
      if (onBlock.event === 'loop') {
        for (const stmt of onBlock.body) {
          code += this.generateStatement(stmt);
        }
      }
    }
    
    // Handle tasks
    for (const task of this.tasks) {
      if (task.interval) {
        code += this.getIndent() + `// Task: ${task.name}\n`;
        code += this.getIndent() + `if (millis() - _task_${task.name}_last >= `;
        code += this.generateTimeValue(task.interval) + ') {\n';
        this.indent++;
        code += this.getIndent() + `_task_${task.name}_last = millis();\n`;
        for (const stmt of task.body) {
          code += this.generateStatement(stmt);
        }
        this.indent--;
        code += this.getIndent() + '}\n';
      } else if (task.isBackground) {
        // Background tasks run in loop
        code += this.getIndent() + `// Background task: ${task.name}\n`;
        for (const stmt of task.body) {
          code += this.generateStatement(stmt);
        }
      }
    }
    
    if (this.loopStatements.length > 0) {
      for (const stmt of this.loopStatements) {
        code += this.generateStatement(stmt);
      }
    }
    this.indent = 0;
    code += '}\n';

    return code;
  }

  generateClassDeclaration(cls) {
    let code = `class ${cls.name} {\n`;
    code += 'public:\n';
    
    // Generate properties
    for (const prop of cls.properties) {
      code += '  ' + this.mapType(prop.propertyType) + ' ' + prop.name;
      if (prop.init) {
        // Note: In-class initialization requires C++11
        code += ' = ' + this.generateExpression(prop.init);
      }
      code += ';\n';
    }
    
    if (cls.properties.length > 0 && (cls.constructor || cls.methods.length > 0)) {
      code += '\n';
    }
    
    // Generate constructor
    if (cls.constructor) {
      code += '  ' + cls.name + '(';
      code += cls.constructor.params.map(p => 
        this.mapType(p.type) + ' ' + p.name
      ).join(', ');
      code += ') {\n';
      
      this.indent = 2;
      for (const stmt of cls.constructor.body) {
        code += this.generateStatement(stmt);
      }
      this.indent = 0;
      
      code += '  }\n';
      
      if (cls.methods.length > 0) {
        code += '\n';
      }
    }
    
    // Generate methods
    for (let i = 0; i < cls.methods.length; i++) {
      const method = cls.methods[i];
      code += '  ' + this.mapType(method.returnType) + ' ' + method.name + '(';
      code += method.params.map(p => 
        this.mapType(p.type) + ' ' + p.name
      ).join(', ');
      code += ') {\n';
      
      this.indent = 2;
      for (const stmt of method.body) {
        code += this.generateStatement(stmt);
      }
      this.indent = 0;
      
      code += '  }';
      if (i < cls.methods.length - 1) {
        code += '\n\n';
      } else {
        code += '\n';
      }
    }
    
    code += '};';
    return code;
  }

  generateFunctionDeclaration(func) {
    const returnType = this.mapType(func.returnType);
    
    let code = `${returnType} ${func.name}(`;
    code += func.params.map(p => 
      this.mapType(p.type) + ' ' + p.name
    ).join(', ');
    code += ') {\n';
    
    this.indent++;
    for (const stmt of func.body) {
      code += this.generateStatement(stmt);
    }
    this.indent--;
    
    code += '}';
    return code;
  }

  mapType(type) {
    const typeMap = {
      'int': 'int',
      'float': 'float',
      'bool': 'bool',
      'string': 'String',
      'void': 'void'
    };
    // If it's not a built-in type, assume it's a class name
    return typeMap[type] || type;
  }

  generateStatement(stmt) {
    switch (stmt.type) {
      case 'VariableDeclaration':
        return this.getIndent() + this.generateVariableDeclaration(stmt) + '\n';
      case 'ExpressionStatement':
        return this.getIndent() + this.generateExpression(stmt.expression) + ';\n';
      case 'IfStatement':
        return this.generateIfStatement(stmt);
      case 'WhileStatement':
        return this.generateWhileStatement(stmt);
      case 'ForStatement':
        return this.generateForStatement(stmt);
      case 'RepeatStatement':
        return this.generateRepeatStatement(stmt);
      case 'ReturnStatement':
        return this.generateReturnStatement(stmt);
      case 'MatchStatement':
        return this.generateMatchStatement(stmt);
      case 'SwitchStatement':
        return this.generateSwitchStatement(stmt);
      case 'EmitStatement':
        return this.generateEmitStatement(stmt);
      case 'WaitStatement':
        return this.generateWaitStatement(stmt);
      case 'TimeoutStatement':
        return this.generateTimeoutStatement(stmt);
      case 'AtomicBlock':
        return this.generateAtomicBlock(stmt);
      case 'CppBlock':
        return this.generateCppBlock(stmt);
      default:
        return '';
    }
  }

  generateVariableDeclaration(varDecl) {
    const typePrefix = varDecl.kind === 'const' ? 'const ' : '';
    const type = this.mapType(varDecl.varType);
    let code = `${typePrefix}${type} ${varDecl.name}`;
    if (varDecl.init) {
      code += ' = ' + this.generateExpression(varDecl.init);
    }
    return code + ';';
  }

  generateIfStatement(stmt) {
    let code = this.getIndent() + 'if (' + this.generateExpression(stmt.test) + ') {\n';
    this.indent++;
    for (const s of stmt.consequent) {
      code += this.generateStatement(s);
    }
    this.indent--;
    code += this.getIndent() + '}';
    
    if (stmt.alternate) {
      code += ' else {\n';
      this.indent++;
      for (const s of stmt.alternate) {
        code += this.generateStatement(s);
      }
      this.indent--;
      code += this.getIndent() + '}';
    }
    
    code += '\n';
    return code;
  }

  generateWhileStatement(stmt) {
    let code = this.getIndent() + 'while (' + this.generateExpression(stmt.test) + ') {\n';
    this.indent++;
    for (const s of stmt.body) {
      code += this.generateStatement(s);
    }
    this.indent--;
    code += this.getIndent() + '}\n';
    return code;
  }

  generateForStatement(stmt) {
    const varType = this.mapType(stmt.varType);
    const init = this.generateExpression(stmt.init);
    const test = this.generateExpression(stmt.test);
    const update = this.generateExpression(stmt.update);
    
    let code = this.getIndent() + `for (${varType} ${stmt.variable} = ${init}; ${test}; ${update}) {\n`;
    
    this.indent++;
    for (const s of stmt.body) {
      code += this.generateStatement(s);
    }
    this.indent--;
    code += this.getIndent() + '}\n';
    return code;
  }

  generateRepeatStatement(stmt) {
    const count = this.generateExpression(stmt.count);
    
    // Generate a for loop: for (int _repeat_i = 0; _repeat_i < count; _repeat_i++)
    let code = this.getIndent() + `for (int _repeat_i = 0; _repeat_i < ${count}; _repeat_i++) {\n`;
    
    this.indent++;
    for (const s of stmt.body) {
      code += this.generateStatement(s);
    }
    this.indent--;
    code += this.getIndent() + '}\n';
    return code;
  }

  generateReturnStatement(stmt) {
    let code = this.getIndent() + 'return';
    if (stmt.argument) {
      code += ' ' + this.generateExpression(stmt.argument);
    }
    return code + ';\n';
  }

  generateExpression(expr) {
    switch (expr.type) {
      case 'Literal':
        return this.generateLiteral(expr);
      case 'Identifier':
        return expr.name;
      case 'BinaryExpression':
        return this.generateBinaryExpression(expr);
      case 'UnaryExpression':
        return this.generateUnaryExpression(expr);
      case 'AssignmentExpression':
        return this.generateExpression(expr.left) + ' = ' + this.generateExpression(expr.right);
      case 'CallExpression':
        return this.generateCallExpression(expr);
      case 'MemberExpression':
        return this.generateMemberExpression(expr);
      case 'ThisExpression':
        return 'this';
      case 'NewExpression':
        return this.generateNewExpression(expr);
      default:
        return '';
    }
  }

  generateMemberExpression(expr) {
    const object = this.generateExpression(expr.object);
    // Use -> for pointer access (this is a pointer in C++)
    if (expr.object.type === 'ThisExpression') {
      return `this->${expr.property}`;
    }
    return `${object}.${expr.property}`;
  }

  generateLiteral(expr) {
    if (expr.valueType === 'string') {
      return `"${expr.value}"`;
    } else if (expr.valueType === 'boolean') {
      return expr.value ? 'true' : 'false';
    }
    return String(expr.value);
  }

  generateBinaryExpression(expr) {
    const left = this.generateExpression(expr.left);
    const right = this.generateExpression(expr.right);
    
    // Convert operators to C++
    const operatorMap = {
      'and': '&&',
      'or': '||',
      '==': '==',
      '!=': '!=',
      '<': '<',
      '>': '>',
      '<=': '<=',
      '>=': '>=',
      '+': '+',
      '-': '-',
      '*': '*',
      '/': '/',
      '%': '%'
    };
    
    const op = operatorMap[expr.operator] || expr.operator;
    return `(${left} ${op} ${right})`;
  }

  generateUnaryExpression(expr) {
    const operatorMap = {
      'not': '!',
      '-': '-'
    };
    const op = operatorMap[expr.operator] || expr.operator;
    return `${op}(${this.generateExpression(expr.argument)})`;
  }

  generateCallExpression(expr) {
    // Safely extract callee name, checking for null
    if (!expr.callee) {
      return '';
    }
    
    let callee;
    if (expr.callee.type === 'MemberExpression') {
      callee = this.generateExpression(expr.callee);
    } else {
      callee = expr.callee.name || this.generateExpression(expr.callee);
    }
    
    const args = expr.arguments.map(arg => this.generateExpression(arg)).join(', ');
    
    // Map built-in functions to Arduino equivalents
    const builtinMap = {
      'print': 'Serial.println',
      'delay': 'delay',
      'millis': 'millis',
      'pinMode': 'pinMode',
      'digitalWrite': 'digitalWrite',
      'digitalRead': 'digitalRead',
      'analogRead': 'analogRead',
      'analogWrite': 'analogWrite'
    };
    
    const funcName = builtinMap[callee] || callee;
    
    // Mark that we need Serial if print is used
    if (callee === 'print') {
      this.needsSerial = true;
    }
    
    return `${funcName}(${args})`;
  }

  generateNewExpression(expr) {
    const args = expr.arguments.map(arg => this.generateExpression(arg)).join(', ');
    return `${expr.className}(${args})`;
  }

  getIndent() {
    return '  '.repeat(this.indent);
  }

  // Generate enum declaration
  generateEnumDeclaration(enumDecl) {
    let code = `enum ${enumDecl.name} {\n`;
    code += '  ' + enumDecl.values.join(',\n  ') + '\n';
    code += '};';
    return code;
  }

  // Generate struct declaration
  generateStructDeclaration(structDecl) {
    let code = `struct ${structDecl.name} {\n`;
    for (const field of structDecl.fields) {
      code += `  ${this.mapType(field.type)} ${field.name};\n`;
    }
    code += '};';
    return code;
  }

  // Generate match statement (transpile to if-else chain)
  generateMatchStatement(stmt) {
    let code = '';
    let isFirst = true;
    
    for (const matchCase of stmt.cases) {
      if (matchCase.pattern.type === 'Wildcard') {
        // This is the default case
        if (!isFirst) {
          code += this.getIndent() + '} else {\n';
        } else {
          code += this.getIndent() + '{\n';
        }
        this.indent++;
        for (const s of matchCase.consequent) {
          code += this.generateStatement(s);
        }
        this.indent--;
        // Don't add closing brace here - it's added at the end
      } else {
        const condition = `${this.generateExpression(stmt.discriminant)} == ${this.generateExpression(matchCase.pattern)}`;
        if (isFirst) {
          code += this.getIndent() + `if (${condition}) {\n`;
          isFirst = false;
        } else {
          code += this.getIndent() + `} else if (${condition}) {\n`;
        }
        this.indent++;
        for (const s of matchCase.consequent) {
          code += this.generateStatement(s);
        }
        this.indent--;
      }
    }
    
    // Always add final closing brace
    code += this.getIndent() + '}\n';
    
    return code;
  }

  // Generate switch statement
  generateSwitchStatement(stmt) {
    let code = this.getIndent() + `switch (${this.generateExpression(stmt.discriminant)}) {\n`;
    
    for (const caseStmt of stmt.cases) {
      code += this.getIndent() + `  case ${this.generateExpression(caseStmt.test)}:\n`;
      this.indent += 2;
      for (const s of caseStmt.consequent) {
        code += this.generateStatement(s);
      }
      code += this.getIndent() + 'break;\n';
      this.indent -= 2;
    }
    
    if (stmt.defaultCase) {
      code += this.getIndent() + '  default:\n';
      this.indent += 2;
      for (const s of stmt.defaultCase) {
        code += this.generateStatement(s);
      }
      code += this.getIndent() + 'break;\n';
      this.indent -= 2;
    }
    
    code += this.getIndent() + '}\n';
    return code;
  }

  // Generate emit statement
  generateEmitStatement(stmt) {
    return this.getIndent() + `_signal_${stmt.signal} = true;\n`;
  }

  // Generate wait statement
  generateWaitStatement(stmt) {
    const delayValue = this.generateTimeValue(stmt.duration);
    return this.getIndent() + `delay(${delayValue});\n`;
  }

  // Generate timeout statement
  generateTimeoutStatement(stmt) {
    const timeoutMs = this.generateTimeValue(stmt.duration);
    const timeVar = `_timeout_${this.timeVarCounter++}`;
    
    let code = this.getIndent() + `unsigned long ${timeVar} = millis();\n`;
    code += this.getIndent() + `while (millis() - ${timeVar} < ${timeoutMs}) {\n`;
    this.indent++;
    for (const s of stmt.body) {
      code += this.generateStatement(s);
    }
    this.indent--;
    code += this.getIndent() + '}\n';
    
    return code;
  }

  // Generate atomic block (use ATOMIC_BLOCK macro or cli/sei)
  generateAtomicBlock(stmt) {
    let code = this.getIndent() + 'noInterrupts();\n';
    for (const s of stmt.body) {
      code += this.generateStatement(s);
    }
    code += this.getIndent() + 'interrupts();\n';
    return code;
  }

  // Generate C++ inline block
  generateCppBlock(stmt) {
    // For C++ blocks, we just output the statements as-is
    // This is a simplified version - in a full implementation,
    // you might want to handle raw C++ code differently
    let code = this.getIndent() + '// Inline C++\n';
    for (const s of stmt.body) {
      code += this.generateStatement(s);
    }
    return code;
  }

  // Helper to convert time literals to milliseconds
  generateTimeValue(expr) {
    if (expr.type === 'Literal' && expr.unit) {
      const value = expr.value;
      switch (expr.unit) {
        case 'ms':
          return String(value);
        case 's':
          return String(value * 1000);
        case 'us':
          return String(value / 1000);
        case 'min':
          return String(value * 60000);
        case 'h':
          return String(value * 3600000);
        default:
          return String(value);
      }
    }
    return this.generateExpression(expr);
  }
}

module.exports = { CodeGenerator };
